#!/usr/bin/env python3
"""Render and validate the Open Novel static documentation set.

This repository predates CAST Docs JSON sources for every page, so the renderer
preserves existing HTML body content and normalizes the document shell, index,
TODO source, and changelist source.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlsplit


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "site" / "docs.json"
TODO_SOURCE = ROOT / "site" / "todo.json"
CHANGELIST_SOURCE = ROOT / "site" / "changelist.json"
GENERATED = "Generated by scripts/render_all_docs.py. Preserve body content; rerun renderer after edits."


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def load_manifest() -> dict:
    return json.loads(read_text(MANIFEST))


def html_paths_from_manifest(manifest: dict) -> list[Path]:
    paths: list[Path] = [ROOT / "index.html", ROOT / "todo.html", ROOT / "changelist.html", ROOT / "CHANGELOG.html"]
    for section in manifest["sections"]:
        for _, href, _, _ in section["items"]:
            if href.endswith(".html"):
                paths.append(ROOT / href.removeprefix("./"))
    seen: set[Path] = set()
    ordered: list[Path] = []
    for path in paths:
        if path not in seen:
            seen.add(path)
            ordered.append(path)
    return ordered


def extract_main_inner(text: str) -> str:
    match = re.search(r"<main class=\"doc\">\s*(.*?)\s*</main>", text, re.S)
    if match:
        inner = match.group(1)
    else:
        body = re.search(r"<body[^>]*>\s*(.*?)\s*</body>", text, re.S)
        inner = body.group(1) if body else text
    inner = re.sub(r"^\s*<nav class=\"doc-meta\"[^>]*>.*?</nav>\s*", "", inner, flags=re.S)
    return inner.strip() + "\n"


def extract_title(path: Path, text: str, inner: str) -> str:
    title = re.search(r"<title>(.*?)</title>", text, re.S)
    if title:
        return html.unescape(re.sub(r"\s+", " ", title.group(1)).strip())
    h1 = re.search(r"<h1[^>]*>(.*?)</h1>", inner, re.S)
    if h1:
        plain = re.sub(r"<[^>]+>", "", h1.group(1))
        return html.unescape(re.sub(r"\s+", " ", plain).strip()) + " - Open Novel"
    return f"{path.name} - Open Novel"


def rel_prefix(path: Path) -> str:
    rel = path.relative_to(ROOT)
    return "../" if len(rel.parts) > 1 else "./"


def render_doc(path: Path, title: str, inner: str, *, nav_path: str | None = None) -> str:
    prefix = rel_prefix(path)
    rel = nav_path or path.relative_to(ROOT).as_posix()
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="open-novel-docs-renderer">
  <title>{html.escape(title)}</title>
  <link rel="stylesheet" href="{prefix}assets/docs.css">
  <script src="{prefix}assets/docs-enhance.js" defer></script>
  <!-- {GENERATED} -->
</head>
<body>
  <main class="doc">
<nav class="doc-meta" aria-label="Document metadata">
  <a href="{prefix}index.html">&larr; Index</a>
  <span>{html.escape(rel)}</span>
</nav>
{inner.strip()}
  </main>
</body>
</html>
"""


def bootstrap_source(target: Path, source_html: Path, kind: str, title: str) -> None:
    if target.exists():
        return
    text = read_text(source_html)
    inner = extract_main_inner(text)
    write_text(
        target,
        json.dumps(
            {
                "schemaVersion": 1,
                "kind": kind,
                "title": title,
                "sourceFormat": "html-body",
                "bodyHtml": inner,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )


def render_source_doc(source: Path, output: Path, fallback: Path, kind: str, title: str) -> str:
    if source.exists():
        data = json.loads(read_text(source))
        if "bodyHtmlLines" in data:
            inner = "\n".join(data["bodyHtmlLines"]) + "\n"
        else:
            inner = data["bodyHtml"]
        doc_title = data.get("title", title)
    else:
        text = read_text(fallback)
        inner = extract_main_inner(text)
        doc_title = extract_title(fallback, text, inner)
    return render_doc(output, doc_title, inner)


def render_compat_changelog() -> str:
    return render_doc(
        ROOT / "CHANGELOG.html",
        "CHANGELOG compatibility redirect - Open Novel",
        """<h1 id="changelog-compat">CHANGELOG.html 已迁移</h1>
<p><code>CHANGELOG.html</code> 保留为兼容入口。规范化的跨文档变更日志现在由 <code>site/changelist.json</code> 渲染到 <a href="./changelist.html">changelist.html</a>。</p>
<p><a href="./changelist.html">打开 changelist.html</a></p>
<script>location.replace('./changelist.html');</script>""",
    )


def render_index(manifest: dict) -> str:
    data_json = json.dumps(manifest["sections"], ensure_ascii=False)
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="open-novel-docs-renderer">
  <title>Open Novel — 文档索引</title>
  <link rel="stylesheet" href="./assets/docs.css">
  <!-- {GENERATED} -->
  <style>
    body {{ padding: 0; background: var(--bg); }}
    .layout {{ display: grid; grid-template-columns: 260px minmax(0, 1fr); min-height: 100vh; }}
    .sidebar {{ position: sticky; top: 0; align-self: start; height: 100vh; padding: 28px 22px; background: var(--paper); border-right: 1px solid var(--border); overflow-y: auto; }}
    .sidebar h1 {{ margin: 0; padding: 0; border: 0; font-size: 18px; }}
    .sidebar .tagline {{ margin: 4px 0 22px; color: var(--muted); font-size: 12.5px; }}
    .sidebar a {{ display: flex; gap: 8px; padding: 5px 8px; border-radius: 4px; color: var(--muted); text-decoration: none; font-size: 13px; }}
    .sidebar a:hover {{ background: var(--code-bg); color: var(--accent-strong); }}
    .group-label {{ margin: 14px 0 4px; padding: 0 8px; color: var(--text); font-weight: 650; font-size: 11px; letter-spacing: .7px; text-transform: uppercase; }}
    .main {{ padding: 0 28px 60px; max-width: 1120px; }}
    .topbar {{ position: sticky; top: 0; z-index: 8; padding: 18px 0 12px; background: var(--bg); }}
    .topbar input {{ width: 100%; padding: 11px 16px; background: var(--paper); border: 1px solid var(--border); border-radius: 6px; font: inherit; font-size: 14.5px; color: var(--text); }}
    .topbar input:focus {{ outline: none; border-color: var(--accent); box-shadow: 0 0 0 3px rgba(29,111,104,.12); }}
    .section {{ margin-top: 26px; scroll-margin-top: 70px; }}
    .section[hidden], .row[hidden], .empty[hidden] {{ display: none; }}
    .section-header {{ display: flex; align-items: baseline; gap: 12px; padding: 0 8px 8px; border-bottom: 2px solid var(--border); }}
    .section-header h2 {{ margin: 0; padding: 0; border: 0; font-size: 13px; letter-spacing: .7px; text-transform: uppercase; color: var(--accent-strong); }}
    .section-header .label, .section-header .count {{ color: var(--muted); font-size: 13px; }}
    .section-header .count {{ margin-left: auto; font-variant-numeric: tabular-nums; }}
    .grid {{ display: grid; grid-template-columns: 70px minmax(180px, max-content) minmax(0, 1fr) auto; column-gap: 16px; }}
    .row {{ display: grid; grid-template-columns: subgrid; grid-column: 1 / -1; align-items: baseline; padding: 9px 8px; border-bottom: 1px solid #ebe3d4; color: inherit; text-decoration: none; }}
    .row:hover, .row.is-focus {{ background: #fbf6ec; }}
    .num {{ color: var(--accent-strong); font-weight: 700; font-size: 12px; font-variant-numeric: tabular-nums; }}
    .title {{ font-weight: 650; font-size: 14.5px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
    .desc {{ color: var(--muted); font-size: 13px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
    .path {{ color: var(--muted); font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, monospace; font-size: 11.5px; opacity: .75; }}
    .empty {{ margin-top: 32px; padding: 26px; text-align: center; color: var(--muted); background: var(--paper); border: 1px dashed var(--border); border-radius: 6px; }}
    @media (max-width: 860px) {{
      .layout {{ grid-template-columns: 1fr; }}
      .sidebar {{ position: static; height: auto; max-height: 280px; padding: 16px 18px; border-right: 0; border-bottom: 1px solid var(--border); }}
      .main {{ padding: 0 18px 40px; }}
      .grid {{ display: block; }}
      .row {{ grid-template-columns: 42px minmax(0, 1fr); row-gap: 2px; }}
      .title, .desc {{ white-space: normal; }}
      .path {{ display: none; }}
    }}
  </style>
</head>
<body>
  <div class="layout">
    <aside class="sidebar">
      <h1>Open Novel</h1>
      <p class="tagline">文档索引 · Strict Profile</p>
      <nav id="toc"></nav>
    </aside>
    <main class="main">
      <div class="topbar">
        <input id="q" type="search" autofocus autocomplete="off" placeholder="过滤: agent / storage / cascade / memory / json">
      </div>
      <div id="docs"></div>
      <p class="empty" id="empty" hidden>没有匹配的文档。</p>
    </main>
  </div>
  <script>
    const DATA = {data_json};
    const esc = (s) => String(s).replace(/[&<>"']/g, c => ({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
    const toc = document.getElementById('toc');
    const docs = document.getElementById('docs');
    const input = document.getElementById('q');
    const empty = document.getElementById('empty');
    toc.innerHTML = DATA.map(sec => `<div class="group-label">${{esc(sec.title)}} <span style="float:right;color:var(--muted);font-weight:400">${{sec.items.length}}</span></div>${{sec.items.map(([id, href, title]) => `<a href="${{esc(href)}}"><span class="num">${{esc(id)}}</span><span>${{esc(title)}}</span></a>`).join('')}}`).join('');
    docs.innerHTML = DATA.map(sec => `<section class="section ${{esc(sec.kind)}}" data-kind="${{esc(sec.kind)}}"><header class="section-header"><h2>${{esc(sec.kind)}}/</h2><span class="label">- ${{esc(sec.label)}}</span><span class="count" data-count></span></header><div class="grid">${{sec.items.map(([id, href, title, desc]) => {{ const path = href.replace(/^\\.\\//, ''); const keys = [id, title, desc, path].join(' ').toLowerCase(); return `<a class="row" href="${{esc(href)}}" data-keys="${{esc(keys)}}"><span class="num">${{esc(id)}}</span><span class="title">${{esc(title)}}</span><span class="desc">${{esc(desc)}}</span><span class="path">${{esc(path)}}</span></a>`; }}).join('')}}</div></section>`).join('');
    const rows = Array.from(docs.querySelectorAll('.row'));
    const sections = Array.from(docs.querySelectorAll('.section'));
    function update() {{
      let total = 0;
      sections.forEach(sec => {{ const n = sec.querySelectorAll('.row:not([hidden])').length; sec.hidden = n === 0; sec.querySelector('[data-count]').textContent = `${{n}} 篇`; total += n; }});
      empty.hidden = total > 0;
    }}
    input.addEventListener('input', () => {{
      const terms = input.value.trim().toLowerCase().split(/\\s+/).filter(Boolean);
      rows.forEach(row => row.hidden = terms.length > 0 && !terms.every(t => row.dataset.keys.includes(t)));
      update();
    }});
    document.addEventListener('keydown', e => {{ if (e.key === '/' && e.target !== input) {{ e.preventDefault(); input.focus(); input.select(); }} }});
    update();
  </script>
</body>
</html>
"""


def render_all(manifest: dict, *, bootstrap: bool) -> dict[Path, str]:
    if bootstrap:
        bootstrap_source(TODO_SOURCE, ROOT / "todo.html", "todo", "TODO - Open Novel")
        bootstrap_source(CHANGELIST_SOURCE, ROOT / "CHANGELOG.html", "changelist", "Changelist - Open Novel")

    rendered: dict[Path, str] = {
        ROOT / "index.html": render_index(manifest),
        ROOT / "todo.html": render_source_doc(TODO_SOURCE, ROOT / "todo.html", ROOT / "todo.html", "todo", "TODO - Open Novel"),
        ROOT / "changelist.html": render_source_doc(CHANGELIST_SOURCE, ROOT / "changelist.html", ROOT / "CHANGELOG.html", "changelist", "Changelist - Open Novel"),
        ROOT / "CHANGELOG.html": render_compat_changelog(),
    }

    for path in html_paths_from_manifest(manifest):
        if path in rendered or path.name == "index.html":
            continue
        if not path.exists():
            raise FileNotFoundError(f"manifest references missing file: {path.relative_to(ROOT)}")
        text = read_text(path)
        inner = extract_main_inner(text)
        title = extract_title(path, text, inner)
        rendered[path] = render_doc(path, title, inner)
    return rendered


def check_fresh(rendered: dict[Path, str]) -> list[str]:
    failures: list[str] = []
    for path, expected in rendered.items():
        if not path.exists():
            failures.append(f"missing rendered file: {path.relative_to(ROOT)}")
        elif read_text(path) != expected:
            failures.append(f"stale rendered file: {path.relative_to(ROOT)}")
    return failures


def collect_local_hrefs(text: str) -> list[str]:
    without_scripts = re.sub(r"<script\b.*?</script>", "", text, flags=re.S | re.I)
    html_hrefs = re.findall(r"""href=["']([^"']+)["']""", without_scripts)
    markdown_hrefs: list[str] = []
    if not re.search(r"<html\b", text, flags=re.I):
        markdown_hrefs = re.findall(r"""(?<!!)\[[^\]]+\]\(([^)]+)\)""", text)
    return html_hrefs + markdown_hrefs


def validate_links(paths: list[Path]) -> list[str]:
    failures: list[str] = []
    for path in paths + [ROOT / "README.md"]:
        if not path.exists():
            continue
        text = read_text(path)
        ids = set(re.findall(r"""id=["']([^"']+)["']""", text))
        for href in collect_local_hrefs(text):
            if href.startswith(("http://", "https://", "mailto:", "javascript:")):
                continue
            if href.startswith("#"):
                if href[1:] and unquote(href[1:]) not in ids:
                    failures.append(f"{path.relative_to(ROOT)}: missing anchor {href}")
                continue
            split = urlsplit(href)
            raw_path = split.path
            if not raw_path:
                continue
            target = (path.parent / unquote(raw_path)).resolve()
            try:
                target.relative_to(ROOT)
            except ValueError:
                failures.append(f"{path.relative_to(ROOT)}: link escapes repo {href}")
                continue
            if not target.exists():
                failures.append(f"{path.relative_to(ROOT)}: missing link target {href}")
                continue
            if split.fragment and target.suffix == ".html":
                target_ids = set(re.findall(r"""id=["']([^"']+)["']""", read_text(target)))
                if unquote(split.fragment) not in target_ids:
                    failures.append(f"{path.relative_to(ROOT)}: missing target anchor {href}")
    return failures


def validate_strict_profile(manifest: dict) -> list[str]:
    failures: list[str] = []
    required = [
        ROOT / "README.md",
        ROOT / "index.html",
        TODO_SOURCE,
        CHANGELIST_SOURCE,
        ROOT / "todo.html",
        ROOT / "changelist.html",
        ROOT / "plan",
        ROOT / "spec",
    ]
    for path in required:
        if not path.exists():
            failures.append(f"strict profile missing: {path.relative_to(ROOT)}")
    index = read_text(ROOT / "index.html") if (ROOT / "index.html").exists() else ""
    for href in ["README.md", "plan/01-overview.html", "spec/00-version-audit.html", "site/todo.json", "site/changelist.json", "todo.html", "changelist.html"]:
        if href not in index:
            failures.append(f"index.html does not link {href}")
    return failures


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bootstrap", action="store_true", help="create site/todo.json and site/changelist.json from existing HTML if missing")
    parser.add_argument("--check", action="store_true", help="fail if generated artifacts are stale")
    parser.add_argument("--validate", action="store_true", help="run local link and strict profile validation")
    args = parser.parse_args(argv)

    manifest = load_manifest()
    rendered = render_all(manifest, bootstrap=args.bootstrap)

    failures: list[str] = []
    if args.check:
        failures.extend(check_fresh(rendered))
    else:
        for path, text in rendered.items():
            write_text(path, text)

    if args.validate:
        failures.extend(validate_strict_profile(manifest))
        failures.extend(validate_links(html_paths_from_manifest(manifest)))

    if failures:
        for failure in failures:
            print(f"[docs] {failure}", file=sys.stderr)
        return 1
    print(f"[docs] ok ({len(rendered)} HTML artifacts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
