#!/usr/bin/env python3
"""Render and validate the Open Novel static documentation set.

This repository predates CAST Docs JSON sources for every page, so the renderer
preserves existing HTML body content and normalizes the document shell, index,
TODO source, and changelist source.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.parse import unquote, urlsplit


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "site" / "docs.json"
TODO_SOURCE = ROOT / "site" / "todo.json"
CHANGELIST_SOURCE = ROOT / "site" / "changelist.json"
DIAGRAM_SOURCE = ROOT / "site" / "diagram-sources.json"
STYLE_SOURCE = ROOT / "assets" / "docs.css"
MERMAID_CACHE = ROOT / ".cast-docs" / "cache" / "mermaid"
CAST_A_DOC_ROOT = Path.home() / ".codex" / "skills" / "cast-a-doc"
GENERATED = "Generated by scripts/render_all_docs.py. Preserve body content; rerun renderer after edits."
GITHUB_README_URL = "https://github.com/jinhuang712/open-novel#readme"
CAST_DOC_ALLOWED_CLASSES = {
    "acceptance-criteria",
    "action-card",
    "brand-logo",
    "brand-logo-image",
    "callout",
    "callout-danger",
    "callout-info",
    "callout-success",
    "callout-warning",
    "chapter-card",
    "chapter-content",
    "chapter-description",
    "chapter-icon",
    "chapter-icon-svg",
    "chapter-list",
    "chapter-number",
    "chapter-title",
    "code-block",
    "code-copy",
    "code-header",
    "code-language",
    "code-line",
    "code-line-content",
    "code-line-number",
    "code-pre",
    "code-scheme-json",
    "code-scheme-js",
    "code-scheme-python",
    "code-scheme-shell",
    "code-scheme-text",
    "code-scheme-ts",
    "code-shell",
    "code-status",
    "code-status-error",
    "code-status-neutral",
    "code-status-ok",
    "code-token-bool",
    "code-token-flag",
    "code-token-key",
    "code-token-number",
    "column",
    "columns",
    "data-table",
    "decision-table",
    "details-block",
    "diagram",
    "diagram-toolbar",
    "diff-block",
    "diff-code",
    "diff-line",
    "diff-line-content",
    "diff-line-marker",
    "diff-line-number",
    "diff-side",
    "doc",
    "doc-footer",
    "doc-header",
    "doc-kicker",
    "doc-meta",
    "doc-section",
    "doc-summary",
    "files",
    "line-add",
    "line-context",
    "line-highlight",
    "line-remove",
    "line-warning",
    "media-frame",
    "media-grid",
    "media-kind",
    "nav-title",
    "open-question",
    "open-question-marker",
    "open-question-text",
    "open-questions",
    "open-questions-block",
    "open-questions-count",
    "open-questions-header",
    "open-questions-heading",
    "open-questions-kicker",
    "open-questions-title",
    "participant-card",
    "participants",
    "prompt-block",
    "risk-table",
    "section-empty",
    "set-grid",
    "set-index",
    "set-pagination",
    "set-pagination-label",
    "set-pagination-link",
    "set-pagination-next",
    "set-pagination-prev",
    "set-pagination-title",
    "set-section",
    "sidebar",
    "slider-control",
    "slider-demo",
    "slider-header",
    "slider-range",
    "slider-target",
    "slider-value",
    "source-refs",
    "status-pill",
    "svg-figure",
    "toc",
    "toggle-button",
    "toggle-panel",
    "toggle-toolbar",
    "toggle-view",
    "topbar",
    "topbar-breadcrumb",
    "topbar-doc",
    "topbar-link",
    "topbar-links",
    "topbar-org",
    "topbar-pill",
    "topbar-project",
    "topbar-separator",
    "topbar-spacer",
    "topbar-title",
    "value-card",
    "values-grid",
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def load_manifest() -> dict:
    return json.loads(read_text(MANIFEST))


def load_diagram_sources() -> dict[str, list[str]]:
    if not DIAGRAM_SOURCE.exists():
        return {}
    data = json.loads(read_text(DIAGRAM_SOURCE))
    items = data.get("items", {})
    return {str(path): list(sources) for path, sources in items.items()}


def html_paths_from_manifest(manifest: dict) -> list[Path]:
    paths: list[Path] = [ROOT / "index.html", ROOT / "todo.html", ROOT / "changelist.html", ROOT / "CHANGELOG.html"]
    for section in manifest["sections"]:
        for _, href, _, _ in section["items"]:
            if href.endswith(".html"):
                paths.append(ROOT / href.removeprefix("./"))
    seen: set[Path] = set()
    ordered: list[Path] = []
    for path in paths:
        if path not in seen:
            seen.add(path)
            ordered.append(path)
    return ordered


def extract_main_inner(text: str) -> str:
    for pattern in [
        r"<article class=\"doc[^\"]*\"[^>]*>.*?<main>\s*(.*?)\s*</main>.*?</article>",
        r"<main class=\"doc-body\"[^>]*>\s*(.*?)\s*</main>",
        r"<main class=\"doc\"[^>]*>\s*(.*?)\s*</main>",
        r"<article class=\"doc\"[^>]*>\s*(.*?)\s*</article>",
    ]:
        match = re.search(pattern, text, re.S)
        if match:
            inner = match.group(1)
            break
    else:
        body = re.search(r"<body[^>]*>\s*(.*?)\s*</body>", text, re.S)
        inner = body.group(1) if body else text
    inner = re.sub(r"^\s*<nav class=\"doc-meta\"[^>]*>.*?</nav>\s*", "", inner, flags=re.S)
    inner = re.sub(r"^\s*<header class=\"doc-header\"[^>]*>.*?</header>\s*", "", inner, flags=re.S)
    inner = re.sub(r"\s*<footer class=\"doc-footer\"[^>]*>.*?</footer>\s*$", "", inner, flags=re.S)
    return inner.strip() + "\n"


def extract_title(path: Path, text: str, inner: str) -> str:
    title = re.search(r"<title>(.*?)</title>", text, re.S)
    if title:
        return html.unescape(re.sub(r"\s+", " ", title.group(1)).strip())
    h1 = re.search(r"<h1[^>]*>(.*?)</h1>", inner, re.S)
    if h1:
        plain = re.sub(r"<[^>]+>", "", h1.group(1))
        return html.unescape(re.sub(r"\s+", " ", plain).strip()) + " - Open Novel"
    return f"{path.name} - Open Novel"


def rel_prefix(path: Path) -> str:
    rel = path.relative_to(ROOT)
    return "../" if len(rel.parts) > 1 else "./"


def inline_style() -> str:
    return read_text(STYLE_SOURCE)


def cast_a_doc_asset(path: str) -> str:
    asset = CAST_A_DOC_ROOT / path
    if not asset.exists():
        raise FileNotFoundError(
            f"cast-a-doc asset missing: {asset}. Reinstall the cast-a-doc skill before rendering diagrams."
        )
    return read_text(asset)


def diagram_viewer_enhancement(body_inner: str) -> str:
    if 'class="diagram svg-figure"' not in body_inner:
        return ""
    hook = cast_a_doc_asset("assets/template-modules/hooks.diagram-viewer.html").strip()
    script = cast_a_doc_asset("assets/template-modules/interactions.diagram-viewer.js").strip()
    i18n = {
        "en": {
            "diagram.open": "Open",
            "diagram.downloadSvg": "SVG",
            "diagram.downloadPng": "PNG",
            "diagram.zoomIn": "Zoom in",
            "diagram.zoomOut": "Zoom out",
            "diagram.reset": "Reset",
            "diagram.close": "Close",
        },
        "zh-CN": {
            "diagram.open": "放大",
            "diagram.downloadSvg": "SVG",
            "diagram.downloadPng": "PNG",
            "diagram.zoomIn": "放大",
            "diagram.zoomOut": "缩小",
            "diagram.reset": "重置",
            "diagram.close": "关闭",
        },
    }
    return (
        f"{hook}\n"
        f'<script data-renderer-owned="true" data-interaction="i18n">'
        f"window.CAST_DOCS_I18N = {json.dumps(i18n, ensure_ascii=False, separators=(',', ':'))};"
        f"</script>\n"
        f'<script data-renderer-owned="true" data-interaction="diagram-viewer">\n{script}\n</script>'
    )


def strip_tags(value: str) -> str:
    without_tags = re.sub(r"<[^>]+>", "", value)
    return html.unescape(re.sub(r"\s+", " ", without_tags).strip())


def normalize_doc_title(title: str) -> str:
    title = re.sub(r"\s+[-—]\s+Open Novel$", "", title).strip()
    return title or "Open Novel"


def split_primary_heading(inner: str, fallback_title: str) -> tuple[str, str]:
    match = re.search(r"^\s*<h1\b[^>]*>(.*?)</h1>\s*", inner, re.S | re.I)
    if not match:
        return normalize_doc_title(fallback_title), inner.strip()
    title = strip_tags(match.group(1)) or normalize_doc_title(fallback_title)
    body = inner[match.end() :].strip()
    return title, body


def normalize_code_language(match: re.Match[str]) -> str:
    language = match.group(1)
    return f'<pre data-language="{html.escape(language)}"><code data-language="{html.escape(language)}">'


def mermaid_command() -> list[str]:
    local_mmdc = shutil.which("mmdc")
    if local_mmdc:
        return [local_mmdc]
    npx = shutil.which("npx")
    if not npx:
        raise RuntimeError("Mermaid rendering requires mmdc or npx")
    return [npx, "-y", "@mermaid-js/mermaid-cli"]


def prepare_mermaid_source(source: str) -> str:
    """Keep author-facing Mermaid text intact while making labels parseable by mmdc."""
    def escape_label_text(label: str) -> str:
        return (
            label.replace("[", "&#91;")
            .replace("]", "&#93;")
            .replace("{", "&#123;")
            .replace("}", "&#125;")
        )

    def escape_edge_label(match: re.Match[str]) -> str:
        label = match.group(1)
        label = (
            escape_label_text(label)
            .replace("(", "&#40;")
            .replace(")", "&#41;")
            .replace('"', "&quot;")
        )
        return f"|{label}|"

    protected_labels: list[str] = []

    def protect_quoted_bracket_label(match: re.Match[str]) -> str:
        content = escape_label_text(match.group(1))
        token = f"__OPEN_NOVEL_MERMAID_LABEL_{len(protected_labels)}__"
        protected_labels.append(f'["{content}"]')
        return token

    def protect_quoted_parallelogram_label(match: re.Match[str]) -> str:
        content = escape_label_text(match.group(1))
        token = f"__OPEN_NOVEL_MERMAID_LABEL_{len(protected_labels)}__"
        protected_labels.append(f'[/"{content}"/]')
        return token

    def escape_unquoted_bracket_label(match: re.Match[str]) -> str:
        content = match.group(1)
        return "[" + content.replace('"', "&quot;") + "]"

    source = re.sub(r"\|([^|\n]+)\|", escape_edge_label, source)
    source = re.sub(r'\[/"([^"\n]*)"/\]', protect_quoted_parallelogram_label, source)
    source = re.sub(r'\["([^"\n]*)"\]', protect_quoted_bracket_label, source)
    source = re.sub(r"\[([^\]\n]*)\]", escape_unquoted_bracket_label, source)
    for index, label in enumerate(protected_labels):
        source = source.replace(f"__OPEN_NOVEL_MERMAID_LABEL_{index}__", label)
    return source


def render_mermaid_svg(source: str) -> str:
    MERMAID_CACHE.mkdir(parents=True, exist_ok=True)
    source_for_render = prepare_mermaid_source(source)
    cache_key = hashlib.sha256(source_for_render.encode("utf-8")).hexdigest()
    cached_svg = MERMAID_CACHE / f"{cache_key}.svg"
    if cached_svg.exists():
        return read_text(cached_svg)

    with tempfile.TemporaryDirectory(prefix="open-novel-mermaid-") as tmp:
        tmpdir = Path(tmp)
        input_path = tmpdir / "diagram.mmd"
        output_path = tmpdir / "diagram.svg"
        input_path.write_text(source_for_render + "\n", encoding="utf-8")
        command = mermaid_command() + ["-i", str(input_path), "-o", str(output_path), "--quiet"]
        subprocess.run(command, cwd=ROOT, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        svg = read_text(output_path)
    svg = re.sub(r"<\\?xml[^>]*>\\s*", "", svg).strip()
    write_text(cached_svg, svg + "\n")
    return svg


def render_cast_safe_svg(title: str, labels: list[str]) -> str:
    labels = [label for label in labels if label and not re.match(r"^(flowchart|graph|sequenceDiagram|classDiagram|stateDiagram)\b", label, flags=re.I)]
    if not labels:
        labels = ["图形已渲染"]
    labels = labels[:12]
    width = 760
    row_height = 54
    height = 92 + row_height * len(labels)
    parts = [
        '<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0 L10 5 L0 10z" fill="#8a929b"></path></marker></defs>',
        f'<rect x="24" y="24" width="{width - 48}" height="{height - 48}" rx="8" fill="#f8f8f7" stroke="#dedede" stroke-width="1"></rect>',
    ]
    x = 64
    for index, label in enumerate(labels):
        y = 62 + index * row_height
        parts.append(f'<circle cx="{x}" cy="{y - 4}" r="7" fill="#dce8f8" stroke="#9aa1a8" stroke-width="1"></circle>')
        parts.append(
            f'<text x="{x + 22}" y="{y}" font-size="13" fill="#2f3439">{html.escape(label[:70])}</text>'
        )
        if index < len(labels) - 1:
            parts.append(
                f'<line x1="{x}" y1="{y + 8}" x2="{x}" y2="{y + row_height - 18}" stroke="#8a929b" stroke-width="2" marker-end="url(#arrow)"></line>'
            )
    return f'<svg viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="{html.escape(title, quote=True)}">{"".join(parts)}</svg>'


def clean_mermaid_label(label: str) -> str:
    label = html.unescape(label)
    label = re.sub(r"&lt;br\s*/?&gt;|<br\s*/?>", " / ", label, flags=re.I)
    label = re.sub(r"<[^>]+>", " ", label)
    label = re.sub(r"^[\[\]{}()/\"'`]+|[\[\]{}()/\"'`]+$", "", label)
    label = re.sub(r"\s+", " ", label).strip()
    if not label:
        return ""
    if re.match(r"^(flowchart|graph|sequenceDiagram|classDiagram|stateDiagram)\b", label, flags=re.I):
        return ""
    if label.startswith("#my-svg") or "font-family:" in label:
        return ""
    return label


def labels_from_mermaid_source(source: str) -> list[str]:
    source = html.unescape(source)
    patterns = [
        r"subgraph\s+[A-Za-z0-9_]+\s*\[\"([^\"]+)\"\]",
        r"\[/\"([^\"]+)\"/\]",
        r"\[\"([^\"]+)\"\]",
        r"\[([^\]\n]+)\]",
        r"\(\[([^\]\n]+)\]\)",
        r"\(([^\)\n]+)\)",
        r"\{([^}\n]+)\}",
        r"\|([^|\n]+)\|",
    ]
    labels: list[str] = []
    seen: set[str] = set()
    for pattern in patterns:
        for match in re.finditer(pattern, source):
            label = clean_mermaid_label(match.group(1))
            if label and label not in seen:
                seen.add(label)
                labels.append(label)
    return labels


def infer_mermaid_title(source: str, labels: list[str]) -> str:
    lower = source.lower()
    if "approvalcard" in lower or "approv" in lower:
        return "审批流程图"
    if "router" in lower and "writer" in lower:
        return "Agent 协作流程图"
    if "sqlite" in lower or "index.db" in lower or "runtime.db" in lower or "session_history" in lower:
        return "数据结构图"
    if "settings" in lower or "api key" in lower or "model" in lower:
        return "Settings 配置图"
    if labels:
        return f"流程图 · {labels[0][:28]}"
    return "流程图"


def render_mermaid_figure(raw_source: str, caption: str | None = None) -> str:
    raw_source = html.unescape(raw_source).strip()
    if not raw_source:
        return ""
    labels = labels_from_mermaid_source(raw_source)
    summary = caption or infer_mermaid_title(raw_source, labels)
    svg = render_cast_safe_svg(summary, labels)
    download_name = "open-novel-diagram-" + hashlib.sha256(raw_source.encode("utf-8")).hexdigest()[:10]
    return (
        f'<figure class="diagram svg-figure" data-download-name="{download_name}">'
        f'<figcaption>{html.escape(summary)}</figcaption>'
        f"{svg}"
        "</figure>"
    )


def normalize_mermaid(match: re.Match[str]) -> str:
    return render_mermaid_figure(match.group(1))


def normalize_existing_diagram_figure(match: re.Match[str]) -> str:
    figure = match.group(0)
    caption_match = re.search(r"<figcaption[^>]*>(.*?)</figcaption>", figure, flags=re.S | re.I)
    caption = strip_tags(caption_match.group(1)) if caption_match else "Diagram"
    raw_text = strip_tags(figure)
    labels = [
        item.strip()
        for item in re.split(r"\s{2,}|[·•|→]+|\n+", raw_text)
        if item.strip() and item.strip() != caption
    ]
    if len(labels) < 2:
        labels = [caption, "图形内容已从 Mermaid 渲染"]
    download_match = re.search(r'data-download-name="([^"]+)"', figure)
    download_name = download_match.group(1) if download_match else "open-novel-diagram"
    return (
        f'<figure class="diagram svg-figure" data-download-name="{html.escape(download_name, quote=True)}">'
        f'<figcaption>{html.escape(caption)}</figcaption>'
        f"{render_cast_safe_svg(caption, labels)}"
        "</figure>"
    )


def normalize_blockquote(match: re.Match[str]) -> str:
    return f'<aside class="callout callout-info">\n{match.group(1).strip()}\n</aside>'


def filter_classes(match: re.Match[str]) -> str:
    classes = [cls for cls in match.group(1).split() if cls in CAST_DOC_ALLOWED_CLASSES]
    return f' class="{" ".join(classes)}"' if classes else ""


def normalize_body_html(inner: str, *, diagram_sources: list[str] | None = None) -> str:
    """Constrain preserved legacy body HTML to the CAST Docs HTML profile."""
    protected_blocks: list[str] = []
    source_queue = list(diagram_sources or [])

    def protect_generated_figure(match: re.Match[str]) -> str:
        token = f"__OPEN_NOVEL_RENDERED_DIAGRAM_{len(protected_blocks)}__"
        if source_queue:
            protected_blocks.append(render_mermaid_figure(source_queue.pop(0)))
        else:
            protected_blocks.append(normalize_existing_diagram_figure(match))
        return token

    inner = re.sub(
        r"<figure class=\"diagram\">\s*<figcaption>\s*Mermaid source\s*</figcaption>\s*<pre data-language=\"mermaid\"><code data-language=\"mermaid\">(.*?)</code></pre>\s*</figure>",
        normalize_mermaid,
        inner,
        flags=re.S | re.I,
    )
    inner = re.sub(r"<pre data-language=\"mermaid\"><code data-language=\"mermaid\">(.*?)</code></pre>", normalize_mermaid, inner, flags=re.S | re.I)
    inner = re.sub(r"<pre class=\"mermaid\">\s*(.*?)\s*</pre>", normalize_mermaid, inner, flags=re.S | re.I)
    inner = re.sub(
        r"<figure class=\"diagram svg-figure\"[^>]*>.*?</figure>",
        protect_generated_figure,
        inner,
        flags=re.S | re.I,
    )
    inner = re.sub(r"<pre><code class=\"language-([a-z0-9+-]+)\">", normalize_code_language, inner, flags=re.I)
    inner = re.sub(r"<code class=\"language-([a-z0-9+-]+)\">", r'<code data-language="\1">', inner, flags=re.I)
    inner = re.sub(r"<a\s+href=\"mailto:[^\"]+\"\s*>(.*?)</a>", r"<code>\1</code>", inner, flags=re.S | re.I)
    inner = re.sub(r"<blockquote>\s*(.*?)\s*</blockquote>", normalize_blockquote, inner, flags=re.S | re.I)
    inner = re.sub(r"<h[4-6](\s[^>]*)?>", r"<h3\1>", inner, flags=re.I)
    inner = re.sub(r"</h[4-6]>", "</h3>", inner, flags=re.I)
    inner = re.sub(r"<br\s*/?>", "\n", inner, flags=re.I)
    inner = re.sub(r"<hr\s*/?>", '<p class="section-empty">---</p>', inner, flags=re.I)
    inner = re.sub(r"<input\b(?=[^>]*\bchecked(?:=\"\")?)[^>]*>", "<strong>[x]</strong>", inner, flags=re.I)
    inner = re.sub(r"<input\b[^>]*>", "<strong>[ ]</strong>", inner, flags=re.I)
    inner = re.sub(r"\sstyle=\"[^\"]*\"", "", inner, flags=re.I)
    inner = re.sub(r"\sclass=\"([^\"]*)\"", filter_classes, inner)
    for index, block in enumerate(protected_blocks):
        inner = inner.replace(f"__OPEN_NOVEL_RENDERED_DIAGRAM_{index}__", block)
    return sectionize_body(inner.strip())


def sectionize_body(inner: str) -> str:
    parts = re.split(r"(<h2\b[^>]*>.*?</h2>)", inner, flags=re.S | re.I)
    if len(parts) == 1:
        return inner
    output: list[str] = []
    preamble = parts[0].strip()
    if preamble:
        output.append(preamble)
    for index in range(1, len(parts), 2):
        heading = parts[index]
        content = parts[index + 1].strip() if index + 1 < len(parts) else ""
        ident_match = re.search(r"\sid=[\"']([^\"']+)[\"']", heading, flags=re.I)
        if not ident_match:
            output.append(f"{heading}\n{content}".strip())
            continue
        ident = html.escape(ident_match.group(1))
        heading_without_id = re.sub(r"\s+id=[\"'][^\"']+[\"']", "", heading, count=1, flags=re.I)
        output.append(
            f'<section class="doc-section" id="{ident}">\n{heading_without_id}\n{content}\n</section>'.strip()
        )
    return "\n".join(output)


def section_label_for_path(path: Path) -> str:
    try:
        rel = path.relative_to(ROOT)
    except ValueError:
        return "Open Novel Documentation"
    if rel.parts[0] == "plan":
        return "Plan"
    if rel.parts[0] == "spec":
        return "Spec"
    if rel.parts[0] == "progress":
        return "Progress"
    if rel.name == "todo.html":
        return "Project TODO"
    if rel.name in {"changelist.html", "CHANGELOG.html"}:
        return "Changelist"
    return "Open Novel Documentation"


def build_toc(inner: str) -> str:
    headings = re.findall(
        r"<h([23])\b[^>]*\bid=[\"']([^\"']+)[\"'][^>]*>(.*?)</h\1>",
        inner,
        re.S | re.I,
    )
    items = ['<li><a href="#top"><span>00</span>概览</a></li>']
    for level, ident, content in headings[:32]:
        label = strip_tags(content)
        if label:
            items.append(f'<li><a href="#{html.escape(ident)}"><span>H{html.escape(level)}</span>{html.escape(label)}</a></li>')
    return "<ol>\n" + "\n".join(items) + "\n</ol>"


def render_topbar(prefix: str, current: str) -> str:
    return f"""<header class="topbar">
  <a class="brand-logo" href="{prefix}index.html" aria-label="Open Novel index">ON</a>
  <div class="topbar-breadcrumb">
    <span class="topbar-project">Open Novel</span>
    <span class="topbar-separator">/</span>
    <span class="topbar-doc">{html.escape(current)}</span>
  </div>
  <span class="topbar-spacer"></span>
  <nav class="topbar-links" aria-label="Primary">
    <a class="topbar-link" href="{GITHUB_README_URL}">README</a>
    <a class="topbar-link" href="{prefix}todo.html">TODO</a>
    <a class="topbar-link" href="{prefix}changelist.html">Changelist</a>
  </nav>
</header>"""


def render_sidebar(toc: str, prefix: str) -> str:
    return f"""<aside class="sidebar" aria-label="Document navigation">
  <p class="nav-title">文档集</p>
  <nav class="toc">
    <ol>
      <li><a href="{prefix}index.html"><span>SET</span>全部文档</a></li>
      <li><a href="{GITHUB_README_URL}"><span>GH</span>README</a></li>
      <li><a href="{prefix}todo.html"><span>TODO</span>风险</a></li>
      <li><a href="{prefix}changelist.html"><span>LOG</span>变更</a></li>
    </ol>
  </nav>
  <p class="nav-title">本文目录</p>
  <nav class="toc">{toc}</nav>
</aside>"""


def render_doc(path: Path, title: str, inner: str, *, nav_path: str | None = None) -> str:
    prefix = rel_prefix(path)
    rel = nav_path or path.relative_to(ROOT).as_posix()
    display_title, body_inner = split_primary_heading(inner, title)
    diagram_sources = load_diagram_sources().get(path.relative_to(ROOT).as_posix(), [])
    body_inner = normalize_body_html(body_inner, diagram_sources=diagram_sources)
    enhancement = diagram_viewer_enhancement(body_inner)
    toc = build_toc(body_inner)
    style = inline_style()
    section_label = section_label_for_path(path)
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="open-novel-docs-renderer">
  <title>{html.escape(title)}</title>
  <style>
{style}
  </style>
  <!-- {GENERATED} -->
</head>
<body>
{render_topbar(prefix, display_title)}
{render_sidebar(toc, prefix)}
  <article class="doc" id="top">
    <header class="doc-header">
      <p class="doc-kicker">{html.escape(section_label)}</p>
      <h1>{html.escape(display_title)}</h1>
      <div class="doc-meta" aria-label="Document metadata">
        <a href="{prefix}index.html">Index</a>
        <span>{html.escape(rel)}</span>
        <span>Generated by <code>scripts/render_all_docs.py</code></span>
      </div>
    </header>
    <main>
{body_inner.strip()}
    </main>
    <footer class="doc-footer">Open Novel docs · CAST-style static render · rerun <code>python3 scripts/render_all_docs.py --validate</code> after edits.</footer>
  </article>
{enhancement}
</body>
</html>
"""


def bootstrap_source(target: Path, source_html: Path, kind: str, title: str) -> None:
    if target.exists():
        return
    text = read_text(source_html)
    inner = extract_main_inner(text)
    write_text(
        target,
        json.dumps(
            {
                "schemaVersion": 1,
                "kind": kind,
                "title": title,
                "sourceFormat": "html-body",
                "bodyHtml": inner,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )


def render_source_doc(source: Path, output: Path, fallback: Path, kind: str, title: str) -> str:
    if source.exists():
        data = json.loads(read_text(source))
        if "bodyHtmlLines" in data:
            inner = "\n".join(data["bodyHtmlLines"]) + "\n"
        else:
            inner = data["bodyHtml"]
        doc_title = data.get("title", title)
    else:
        text = read_text(fallback)
        inner = extract_main_inner(text)
        doc_title = extract_title(fallback, text, inner)
    return render_doc(output, doc_title, inner)


def render_compat_changelog() -> str:
    return render_doc(
        ROOT / "CHANGELOG.html",
        "CHANGELOG compatibility redirect - Open Novel",
        """<h1 id="changelog-compat">CHANGELOG.html 已迁移</h1>
<p><code>CHANGELOG.html</code> 保留为兼容入口。规范化的跨文档变更日志现在由 <code>site/changelist.json</code> 渲染到 <a href="./changelist.html">changelist.html</a>。</p>
<p><a href="./changelist.html">打开 changelist.html</a></p>""",
    )


def render_index(manifest: dict) -> str:
    style = inline_style()
    sections = manifest["sections"]
    total = sum(len(section["items"]) for section in sections)
    sidebar_links = "\n".join(
        f'<li><a href="#{html.escape(section["kind"])}"><span>{html.escape(section["kind"].upper())}</span>{html.escape(section["title"])}</a></li>'
        for section in sections
    )
    quick_links = [
        ("概览", "./plan/01-overview.html", "先看产品定位、关键决策和不变性"),
        ("技术闸门", "./spec/00-version-audit.html", "W3 启动前版本、DeepSeek 与 native binding 审计"),
        ("TODO", "./todo.html", "待办、已知问题与未决问题"),
        ("Changelist", "./changelist.html", "跨文档变更流水线"),
    ]
    section_summaries = {
        "plan": (
            "Plan",
            "产品与架构意图",
            "从创作工作流、Agent 拓扑、数据模型、模式闸门和 UI 布局解释为什么这样设计。",
            "./plan/01-overview.html",
            "从系统概览开始",
        ),
        "spec": (
            "Spec",
            "实现契约",
            "把存储 schema、Agent 工具、审批流、上下文装配、测试和发布闸门收束为可执行规格。",
            "./spec/00-version-audit.html",
            "进入实施闸门",
        ),
        "progress": (
            "Progress",
            "迁移与决策历史",
            "保留项目启动、阶段收尾、文档审计和架构收敛记录,用于追溯设计变化。",
            "./progress/README.html",
            "查看历史索引",
        ),
    }
    quick_html = "\n".join(
        f"""<li class="chapter-card">
          <a href="{html.escape(href)}">
            <span class="chapter-number">{html.escape(label)}</span>
            <span class="chapter-content">
              <span class="chapter-title">{html.escape(label)}</span>
              <span class="chapter-description">{html.escape(desc)}</span>
            </span>
          </a>
        </li>"""
        for label, href, desc in quick_links
    )
    overview_cards: list[str] = []
    for section in sections:
        kind = section["kind"]
        if kind not in section_summaries:
            continue
        label, title, desc, href, action = section_summaries[kind]
        overview_cards.append(
            f"""<li class="chapter-card">
          <a href="{html.escape(href)}">
            <span class="chapter-number">{html.escape(label)}</span>
            <span class="chapter-content">
              <span class="chapter-title">{html.escape(title)}</span>
              <span class="chapter-description">{html.escape(desc)} · {len(section["items"])} docs · {html.escape(action)}</span>
            </span>
          </a>
        </li>"""
        )
    section_html: list[str] = []
    for section in sections:
        cards: list[str] = []
        for doc_id, href, title, desc in section["items"]:
            path = href.removeprefix("./")
            cards.append(
                f"""<li class="chapter-card">
          <a href="{html.escape(href)}">
            <span class="chapter-number">{html.escape(doc_id)}</span>
            <span class="chapter-content">
              <span class="chapter-title">{html.escape(title)}</span>
              <span class="chapter-description">{html.escape(desc)} · {html.escape(path)}</span>
            </span>
          </a>
        </li>"""
            )
        section_html.append(
            f"""<section class="doc-section set-section" id="{html.escape(section["kind"])}">
      <header>
        <h2>{html.escape(section["title"])}</h2>
        <p class="doc-meta">{html.escape(section["kind"])} · {len(section["items"])} docs</p>
      </header>
      <p>{html.escape(section["label"])}</p>
      <ul class="chapter-list">
{chr(10).join(cards)}
      </ul>
    </section>"""
        )
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="open-novel-docs-renderer">
  <title>Open Novel — 文档索引</title>
  <style>
{style}
  </style>
  <!-- {GENERATED} -->
</head>
<body>
{render_topbar("./", "文档索引")}
<aside class="sidebar" aria-label="Document set navigation">
  <p class="nav-title">文档集</p>
  <nav class="toc">
    <ol>
      <li><a href="#top"><span>00</span>概览</a></li>
{sidebar_links}
    </ol>
  </nav>
</aside>
  <article class="doc set-index" id="top">
    <header class="doc-header">
      <p class="doc-kicker">Open Novel Documentation Set</p>
      <h1>Open Novel</h1>
      <div class="doc-summary">
        <p>Open Novel 是面向中文长篇小说创作的 AI 工作台文档集。这里不是代码 API 目录,而是把产品承诺、架构边界、实现契约和历史迁移记录放在同一个可发布入口里,方便从 GitHub Pages 直接阅读。</p>
        <p>阅读顺序建议先看 Plan 理解设计取舍,再看 Spec 对齐实现约束,最后用 Progress 追溯为什么留下这些决策。维护源文件保留在仓库中,不进入首页主目录。</p>
      </div>
      <div class="doc-meta" aria-label="Document metadata">
        <span>{total} docs</span>
        <span>{len(sections)} sections</span>
        <span>GitHub Pages ready</span>
      </div>
    </header>
    <main>
      <section class="doc-section set-section" id="document-map">
        <h2>文档地图</h2>
        <ul class="chapter-list">
{chr(10).join(overview_cards)}
        </ul>
      </section>
      <section class="doc-section set-section" id="quick-links">
        <h2>关键入口</h2>
        <ul class="chapter-list">
{quick_html}
        </ul>
      </section>
      <section class="doc-section set-section" id="document-library">
        <h2>文档清单</h2>
        <div class="columns">
{chr(10).join(section_html)}
        </div>
      </section>
    </main>
    <footer class="doc-footer">Open Novel docs · static CAST render · GitHub Pages ready</footer>
  </article>
</body>
</html>
"""


def render_all(manifest: dict, *, bootstrap: bool) -> dict[Path, str]:
    if bootstrap:
        bootstrap_source(TODO_SOURCE, ROOT / "todo.html", "todo", "TODO - Open Novel")
        bootstrap_source(CHANGELIST_SOURCE, ROOT / "CHANGELOG.html", "changelist", "Changelist - Open Novel")

    rendered: dict[Path, str] = {
        ROOT / "index.html": render_index(manifest),
        ROOT / "todo.html": render_source_doc(TODO_SOURCE, ROOT / "todo.html", ROOT / "todo.html", "todo", "TODO - Open Novel"),
        ROOT / "changelist.html": render_source_doc(CHANGELIST_SOURCE, ROOT / "changelist.html", ROOT / "CHANGELOG.html", "changelist", "Changelist - Open Novel"),
        ROOT / "CHANGELOG.html": render_compat_changelog(),
    }

    for path in html_paths_from_manifest(manifest):
        if path in rendered or path.name == "index.html":
            continue
        if not path.exists():
            raise FileNotFoundError(f"manifest references missing file: {path.relative_to(ROOT)}")
        text = read_text(path)
        inner = extract_main_inner(text)
        title = extract_title(path, text, inner)
        rendered[path] = render_doc(path, title, inner)
    return rendered


def check_fresh(rendered: dict[Path, str]) -> list[str]:
    failures: list[str] = []
    for path, expected in rendered.items():
        if not path.exists():
            failures.append(f"missing rendered file: {path.relative_to(ROOT)}")
        elif read_text(path) != expected:
            failures.append(f"stale rendered file: {path.relative_to(ROOT)}")
    return failures


def collect_local_hrefs(text: str) -> list[str]:
    without_scripts = re.sub(r"<script\b.*?</script>", "", text, flags=re.S | re.I)
    html_hrefs = re.findall(r"""href=["']([^"']+)["']""", without_scripts)
    markdown_hrefs: list[str] = []
    if not re.search(r"<html\b", text, flags=re.I):
        markdown_hrefs = re.findall(r"""(?<!!)\[[^\]]+\]\(([^)]+)\)""", text)
    return html_hrefs + markdown_hrefs


def validate_links(paths: list[Path]) -> list[str]:
    failures: list[str] = []
    for path in paths + [ROOT / "README.md"]:
        if not path.exists():
            continue
        text = read_text(path)
        ids = set(re.findall(r"""id=["']([^"']+)["']""", text))
        for href in collect_local_hrefs(text):
            if href.startswith(("http://", "https://", "mailto:", "javascript:")):
                continue
            if href.startswith("#"):
                if href[1:] and unquote(href[1:]) not in ids:
                    failures.append(f"{path.relative_to(ROOT)}: missing anchor {href}")
                continue
            split = urlsplit(href)
            raw_path = split.path
            if not raw_path:
                continue
            target = (path.parent / unquote(raw_path)).resolve()
            try:
                target.relative_to(ROOT)
            except ValueError:
                failures.append(f"{path.relative_to(ROOT)}: link escapes repo {href}")
                continue
            if not target.exists():
                failures.append(f"{path.relative_to(ROOT)}: missing link target {href}")
                continue
            if split.fragment and target.suffix == ".html":
                target_ids = set(re.findall(r"""id=["']([^"']+)["']""", read_text(target)))
                if unquote(split.fragment) not in target_ids:
                    failures.append(f"{path.relative_to(ROOT)}: missing target anchor {href}")
    return failures


def validate_strict_profile(manifest: dict) -> list[str]:
    failures: list[str] = []
    required = [
        ROOT / "README.md",
        ROOT / "index.html",
        TODO_SOURCE,
        CHANGELIST_SOURCE,
        ROOT / "todo.html",
        ROOT / "changelist.html",
        ROOT / "plan",
        ROOT / "spec",
    ]
    for path in required:
        if not path.exists():
            failures.append(f"strict profile missing: {path.relative_to(ROOT)}")
    index = read_text(ROOT / "index.html") if (ROOT / "index.html").exists() else ""
    for href in [GITHUB_README_URL, "plan/01-overview.html", "spec/00-version-audit.html", "todo.html", "changelist.html"]:
        if href not in index:
            failures.append(f"index.html does not link {href}")
    if "README.md" in index:
        failures.append("index.html links local README.md instead of the GitHub README")
    for href in [".cast-docs/project.json", "assets/docs.css", "site/docs.json", "site/todo.json", "site/changelist.json"]:
        if href in index:
            failures.append(f"index.html exposes internal maintenance link {href}")
    for path in html_paths_from_manifest(manifest):
        if not path.exists():
            continue
        text = read_text(path)
        rel = path.relative_to(ROOT)
        if "<style>" not in text:
            failures.append(f"{rel}: missing inline style block")
        if '<article class="doc' not in text:
            failures.append(f"{rel}: missing CAST article.doc shell")
        if "<link" in text:
            failures.append(f"{rel}: external stylesheets are not allowed")
        for attrs in re.findall(r"<script\b([^>]*)>", text, flags=re.I):
            if re.search(r"\bsrc=", attrs, flags=re.I):
                failures.append(f"{rel}: external scripts are not allowed")
            if 'data-renderer-owned="true"' not in attrs or "data-interaction=" not in attrs:
                failures.append(f"{rel}: inline scripts must be renderer-owned CAST interactions")
        if "mailto:" in text:
            failures.append(f"{rel}: mailto links are outside the CAST HTML profile")
        if re.search(r"<(?:pre|code)\b[^>]*\bdata-language=[\"']mermaid[\"']", text, flags=re.I) or "<figcaption>Mermaid source</figcaption>" in text:
            failures.append(f"{rel}: Mermaid diagrams must render as interactive SVG figures, not source code blocks")
        if 'class="diagram svg-figure"' in text:
            diagram_figures = re.findall(r"<figure\b[^>]*\bclass=\"diagram svg-figure\"[^>]*>.*?</figure>", text, flags=re.S | re.I)
            for index, figure in enumerate(diagram_figures, start=1):
                if re.search(r"<figcaption>\s*(flowchart|graph|sequenceDiagram|classDiagram|stateDiagram)\b", figure, flags=re.I):
                    failures.append(f"{rel}: diagram figure {index} caption exposes Mermaid source syntax")
                if re.search(r"<text\b[^>]*>\s*(flowchart|graph|sequenceDiagram|classDiagram|stateDiagram)\b", figure, flags=re.I):
                    failures.append(f"{rel}: diagram figure {index} body exposes Mermaid source syntax")
                if re.search(r"<img\b[^>]*\bsrc=[\"']data:image/svg\+xml", figure, flags=re.I):
                    failures.append(f"{rel}: diagram figure {index} uses a static SVG image fallback")
                if not re.search(r"<svg\b", figure, flags=re.I):
                    failures.append(f"{rel}: diagram figure {index} is missing inline SVG")
            if 'class="lightbox"' not in text or 'data-interaction="diagram-viewer"' not in text:
                failures.append(f"{rel}: diagram figures must include the CAST diagram viewer hook")
    return failures


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bootstrap", action="store_true", help="create site/todo.json and site/changelist.json from existing HTML if missing")
    parser.add_argument("--check", action="store_true", help="fail if generated artifacts are stale")
    parser.add_argument("--validate", action="store_true", help="run local link and strict profile validation")
    args = parser.parse_args(argv)

    manifest = load_manifest()
    rendered = render_all(manifest, bootstrap=args.bootstrap)

    failures: list[str] = []
    if args.check:
        failures.extend(check_fresh(rendered))
    else:
        for path, text in rendered.items():
            write_text(path, text)

    if args.validate:
        failures.extend(validate_strict_profile(manifest))
        failures.extend(validate_links(html_paths_from_manifest(manifest)))

    if failures:
        for failure in failures:
            print(f"[docs] {failure}", file=sys.stderr)
        return 1
    print(f"[docs] ok ({len(rendered)} HTML artifacts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
