#!/usr/bin/env python3
"""Render and validate the Open Novel static documentation set.

This repository predates CAST Docs JSON sources for every page, so the renderer
preserves existing HTML body content and normalizes the document shell, index,
TODO source, and changelist source.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlsplit


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "site" / "docs.json"
TODO_SOURCE = ROOT / "site" / "todo.json"
CHANGELIST_SOURCE = ROOT / "site" / "changelist.json"
STYLE_SOURCE = ROOT / "assets" / "docs.css"
GENERATED = "Generated by scripts/render_all_docs.py. Preserve body content; rerun renderer after edits."
GITHUB_README_URL = "https://github.com/jinhuang712/open-novel#readme"
CAST_DOC_ALLOWED_CLASSES = {
    "acceptance-criteria",
    "action-card",
    "brand-logo",
    "brand-logo-image",
    "callout",
    "callout-danger",
    "callout-info",
    "callout-success",
    "callout-warning",
    "chapter-card",
    "chapter-content",
    "chapter-description",
    "chapter-icon",
    "chapter-icon-svg",
    "chapter-list",
    "chapter-number",
    "chapter-title",
    "code-block",
    "code-copy",
    "code-header",
    "code-language",
    "code-line",
    "code-line-content",
    "code-line-number",
    "code-pre",
    "code-scheme-json",
    "code-scheme-js",
    "code-scheme-python",
    "code-scheme-shell",
    "code-scheme-text",
    "code-scheme-ts",
    "code-shell",
    "code-status",
    "code-status-error",
    "code-status-neutral",
    "code-status-ok",
    "code-token-bool",
    "code-token-flag",
    "code-token-key",
    "code-token-number",
    "column",
    "columns",
    "data-table",
    "decision-table",
    "details-block",
    "diagram",
    "diagram-toolbar",
    "diff-block",
    "diff-code",
    "diff-line",
    "diff-line-content",
    "diff-line-marker",
    "diff-line-number",
    "diff-side",
    "doc",
    "doc-footer",
    "doc-header",
    "doc-kicker",
    "doc-meta",
    "doc-section",
    "doc-summary",
    "files",
    "line-add",
    "line-context",
    "line-highlight",
    "line-remove",
    "line-warning",
    "media-frame",
    "media-grid",
    "media-kind",
    "nav-title",
    "open-question",
    "open-question-marker",
    "open-question-text",
    "open-questions",
    "open-questions-block",
    "open-questions-count",
    "open-questions-header",
    "open-questions-heading",
    "open-questions-kicker",
    "open-questions-title",
    "participant-card",
    "participants",
    "prompt-block",
    "risk-table",
    "section-empty",
    "set-grid",
    "set-index",
    "set-pagination",
    "set-pagination-label",
    "set-pagination-link",
    "set-pagination-next",
    "set-pagination-prev",
    "set-pagination-title",
    "set-section",
    "sidebar",
    "slider-control",
    "slider-demo",
    "slider-header",
    "slider-range",
    "slider-target",
    "slider-value",
    "source-refs",
    "status-pill",
    "svg-figure",
    "toc",
    "toggle-button",
    "toggle-panel",
    "toggle-toolbar",
    "toggle-view",
    "topbar",
    "topbar-breadcrumb",
    "topbar-doc",
    "topbar-link",
    "topbar-links",
    "topbar-org",
    "topbar-pill",
    "topbar-project",
    "topbar-separator",
    "topbar-spacer",
    "topbar-title",
    "value-card",
    "values-grid",
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def load_manifest() -> dict:
    return json.loads(read_text(MANIFEST))


def html_paths_from_manifest(manifest: dict) -> list[Path]:
    paths: list[Path] = [ROOT / "index.html", ROOT / "todo.html", ROOT / "changelist.html", ROOT / "CHANGELOG.html"]
    for section in manifest["sections"]:
        for _, href, _, _ in section["items"]:
            if href.endswith(".html"):
                paths.append(ROOT / href.removeprefix("./"))
    seen: set[Path] = set()
    ordered: list[Path] = []
    for path in paths:
        if path not in seen:
            seen.add(path)
            ordered.append(path)
    return ordered


def extract_main_inner(text: str) -> str:
    for pattern in [
        r"<article class=\"doc[^\"]*\"[^>]*>.*?<main>\s*(.*?)\s*</main>.*?</article>",
        r"<main class=\"doc-body\"[^>]*>\s*(.*?)\s*</main>",
        r"<main class=\"doc\"[^>]*>\s*(.*?)\s*</main>",
        r"<article class=\"doc\"[^>]*>\s*(.*?)\s*</article>",
    ]:
        match = re.search(pattern, text, re.S)
        if match:
            inner = match.group(1)
            break
    else:
        body = re.search(r"<body[^>]*>\s*(.*?)\s*</body>", text, re.S)
        inner = body.group(1) if body else text
    inner = re.sub(r"^\s*<nav class=\"doc-meta\"[^>]*>.*?</nav>\s*", "", inner, flags=re.S)
    inner = re.sub(r"^\s*<header class=\"doc-header\"[^>]*>.*?</header>\s*", "", inner, flags=re.S)
    inner = re.sub(r"\s*<footer class=\"doc-footer\"[^>]*>.*?</footer>\s*$", "", inner, flags=re.S)
    return inner.strip() + "\n"


def extract_title(path: Path, text: str, inner: str) -> str:
    title = re.search(r"<title>(.*?)</title>", text, re.S)
    if title:
        return html.unescape(re.sub(r"\s+", " ", title.group(1)).strip())
    h1 = re.search(r"<h1[^>]*>(.*?)</h1>", inner, re.S)
    if h1:
        plain = re.sub(r"<[^>]+>", "", h1.group(1))
        return html.unescape(re.sub(r"\s+", " ", plain).strip()) + " - Open Novel"
    return f"{path.name} - Open Novel"


def rel_prefix(path: Path) -> str:
    rel = path.relative_to(ROOT)
    return "../" if len(rel.parts) > 1 else "./"


def inline_style() -> str:
    return read_text(STYLE_SOURCE)


def strip_tags(value: str) -> str:
    without_tags = re.sub(r"<[^>]+>", "", value)
    return html.unescape(re.sub(r"\s+", " ", without_tags).strip())


def normalize_doc_title(title: str) -> str:
    title = re.sub(r"\s+[-—]\s+Open Novel$", "", title).strip()
    return title or "Open Novel"


def split_primary_heading(inner: str, fallback_title: str) -> tuple[str, str]:
    match = re.search(r"^\s*<h1\b[^>]*>(.*?)</h1>\s*", inner, re.S | re.I)
    if not match:
        return normalize_doc_title(fallback_title), inner.strip()
    title = strip_tags(match.group(1)) or normalize_doc_title(fallback_title)
    body = inner[match.end() :].strip()
    return title, body


def normalize_code_language(match: re.Match[str]) -> str:
    language = match.group(1)
    return f'<pre data-language="{html.escape(language)}"><code data-language="{html.escape(language)}">'


def normalize_mermaid(match: re.Match[str]) -> str:
    raw_source = html.unescape(match.group(1)).strip()
    escaped = html.escape(raw_source, quote=False)
    return (
        '<figure class="diagram">'
        '<figcaption>Mermaid source</figcaption>'
        f'<pre data-language="mermaid"><code data-language="mermaid">{escaped}</code></pre>'
        "</figure>"
    )


def normalize_blockquote(match: re.Match[str]) -> str:
    return f'<aside class="callout callout-info">\n{match.group(1).strip()}\n</aside>'


def filter_classes(match: re.Match[str]) -> str:
    classes = [cls for cls in match.group(1).split() if cls in CAST_DOC_ALLOWED_CLASSES]
    return f' class="{" ".join(classes)}"' if classes else ""


def normalize_body_html(inner: str) -> str:
    """Constrain preserved legacy body HTML to the CAST Docs HTML profile."""
    inner = re.sub(r"<pre class=\"mermaid\">\s*(.*?)\s*</pre>", normalize_mermaid, inner, flags=re.S | re.I)
    inner = re.sub(r"<pre><code class=\"language-([a-z0-9+-]+)\">", normalize_code_language, inner, flags=re.I)
    inner = re.sub(r"<code class=\"language-([a-z0-9+-]+)\">", r'<code data-language="\1">', inner, flags=re.I)
    inner = re.sub(r"<a\s+href=\"mailto:[^\"]+\"\s*>(.*?)</a>", r"<code>\1</code>", inner, flags=re.S | re.I)
    inner = re.sub(r"<blockquote>\s*(.*?)\s*</blockquote>", normalize_blockquote, inner, flags=re.S | re.I)
    inner = re.sub(r"<h[4-6](\s[^>]*)?>", r"<h3\1>", inner, flags=re.I)
    inner = re.sub(r"</h[4-6]>", "</h3>", inner, flags=re.I)
    inner = re.sub(r"<br\s*/?>", "\n", inner, flags=re.I)
    inner = re.sub(r"<hr\s*/?>", '<p class="section-empty">---</p>', inner, flags=re.I)
    inner = re.sub(r"<input\b(?=[^>]*\bchecked(?:=\"\")?)[^>]*>", "<strong>[x]</strong>", inner, flags=re.I)
    inner = re.sub(r"<input\b[^>]*>", "<strong>[ ]</strong>", inner, flags=re.I)
    inner = re.sub(r"\sstyle=\"[^\"]*\"", "", inner, flags=re.I)
    inner = re.sub(r"\sclass=\"([^\"]*)\"", filter_classes, inner)
    return sectionize_body(inner.strip())


def sectionize_body(inner: str) -> str:
    parts = re.split(r"(<h2\b[^>]*>.*?</h2>)", inner, flags=re.S | re.I)
    if len(parts) == 1:
        return inner
    output: list[str] = []
    preamble = parts[0].strip()
    if preamble:
        output.append(preamble)
    for index in range(1, len(parts), 2):
        heading = parts[index]
        content = parts[index + 1].strip() if index + 1 < len(parts) else ""
        ident_match = re.search(r"\sid=[\"']([^\"']+)[\"']", heading, flags=re.I)
        if not ident_match:
            output.append(f"{heading}\n{content}".strip())
            continue
        ident = html.escape(ident_match.group(1))
        heading_without_id = re.sub(r"\s+id=[\"'][^\"']+[\"']", "", heading, count=1, flags=re.I)
        output.append(
            f'<section class="doc-section" id="{ident}">\n{heading_without_id}\n{content}\n</section>'.strip()
        )
    return "\n".join(output)


def section_label_for_path(path: Path) -> str:
    try:
        rel = path.relative_to(ROOT)
    except ValueError:
        return "Open Novel Documentation"
    if rel.parts[0] == "plan":
        return "Plan"
    if rel.parts[0] == "spec":
        return "Spec"
    if rel.parts[0] == "progress":
        return "Progress"
    if rel.name == "todo.html":
        return "Project TODO"
    if rel.name in {"changelist.html", "CHANGELOG.html"}:
        return "Changelist"
    return "Open Novel Documentation"


def build_toc(inner: str) -> str:
    headings = re.findall(
        r"<h([23])\b[^>]*\bid=[\"']([^\"']+)[\"'][^>]*>(.*?)</h\1>",
        inner,
        re.S | re.I,
    )
    items = ['<li><a href="#top"><span>00</span>概览</a></li>']
    for level, ident, content in headings[:32]:
        label = strip_tags(content)
        if label:
            items.append(f'<li><a href="#{html.escape(ident)}"><span>H{html.escape(level)}</span>{html.escape(label)}</a></li>')
    return "<ol>\n" + "\n".join(items) + "\n</ol>"


def render_topbar(prefix: str, current: str) -> str:
    return f"""<header class="topbar">
  <a class="brand-logo" href="{prefix}index.html" aria-label="Open Novel index">ON</a>
  <div class="topbar-breadcrumb">
    <span class="topbar-project">Open Novel</span>
    <span class="topbar-separator">/</span>
    <span class="topbar-doc">{html.escape(current)}</span>
  </div>
  <span class="topbar-spacer"></span>
  <nav class="topbar-links" aria-label="Primary">
    <a class="topbar-link" href="{GITHUB_README_URL}">README</a>
    <a class="topbar-link" href="{prefix}todo.html">TODO</a>
    <a class="topbar-link" href="{prefix}changelist.html">Changelist</a>
  </nav>
</header>"""


def render_sidebar(toc: str, prefix: str) -> str:
    return f"""<aside class="sidebar" aria-label="Document navigation">
  <p class="nav-title">文档集</p>
  <nav class="toc">
    <ol>
      <li><a href="{prefix}index.html"><span>SET</span>全部文档</a></li>
      <li><a href="{GITHUB_README_URL}"><span>GH</span>README</a></li>
      <li><a href="{prefix}todo.html"><span>TODO</span>风险</a></li>
      <li><a href="{prefix}changelist.html"><span>LOG</span>变更</a></li>
    </ol>
  </nav>
  <p class="nav-title">本文目录</p>
  <nav class="toc">{toc}</nav>
</aside>"""


def render_doc(path: Path, title: str, inner: str, *, nav_path: str | None = None) -> str:
    prefix = rel_prefix(path)
    rel = nav_path or path.relative_to(ROOT).as_posix()
    display_title, body_inner = split_primary_heading(inner, title)
    body_inner = normalize_body_html(body_inner)
    toc = build_toc(body_inner)
    style = inline_style()
    section_label = section_label_for_path(path)
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="open-novel-docs-renderer">
  <title>{html.escape(title)}</title>
  <style>
{style}
  </style>
  <!-- {GENERATED} -->
</head>
<body>
{render_topbar(prefix, display_title)}
{render_sidebar(toc, prefix)}
  <article class="doc" id="top">
    <header class="doc-header">
      <p class="doc-kicker">{html.escape(section_label)}</p>
      <h1>{html.escape(display_title)}</h1>
      <div class="doc-meta" aria-label="Document metadata">
        <a href="{prefix}index.html">Index</a>
        <span>{html.escape(rel)}</span>
        <span>Generated by <code>scripts/render_all_docs.py</code></span>
      </div>
    </header>
    <main>
{body_inner.strip()}
    </main>
    <footer class="doc-footer">Open Novel docs · CAST-style static render · rerun <code>python3 scripts/render_all_docs.py --validate</code> after edits.</footer>
  </article>
</body>
</html>
"""


def bootstrap_source(target: Path, source_html: Path, kind: str, title: str) -> None:
    if target.exists():
        return
    text = read_text(source_html)
    inner = extract_main_inner(text)
    write_text(
        target,
        json.dumps(
            {
                "schemaVersion": 1,
                "kind": kind,
                "title": title,
                "sourceFormat": "html-body",
                "bodyHtml": inner,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )


def render_source_doc(source: Path, output: Path, fallback: Path, kind: str, title: str) -> str:
    if source.exists():
        data = json.loads(read_text(source))
        if "bodyHtmlLines" in data:
            inner = "\n".join(data["bodyHtmlLines"]) + "\n"
        else:
            inner = data["bodyHtml"]
        doc_title = data.get("title", title)
    else:
        text = read_text(fallback)
        inner = extract_main_inner(text)
        doc_title = extract_title(fallback, text, inner)
    return render_doc(output, doc_title, inner)


def render_compat_changelog() -> str:
    return render_doc(
        ROOT / "CHANGELOG.html",
        "CHANGELOG compatibility redirect - Open Novel",
        """<h1 id="changelog-compat">CHANGELOG.html 已迁移</h1>
<p><code>CHANGELOG.html</code> 保留为兼容入口。规范化的跨文档变更日志现在由 <code>site/changelist.json</code> 渲染到 <a href="./changelist.html">changelist.html</a>。</p>
<p><a href="./changelist.html">打开 changelist.html</a></p>""",
    )


def render_index(manifest: dict) -> str:
    style = inline_style()
    sections = manifest["sections"]
    total = sum(len(section["items"]) for section in sections)
    sidebar_links = "\n".join(
        f'<li><a href="#{html.escape(section["kind"])}"><span>{html.escape(section["kind"].upper())}</span>{html.escape(section["title"])}</a></li>'
        for section in sections
    )
    quick_links = [
        ("概览", "./plan/01-overview.html", "先看产品定位、关键决策和不变性"),
        ("技术闸门", "./spec/00-version-audit.html", "W3 启动前版本、DeepSeek 与 native binding 审计"),
        ("TODO", "./todo.html", "待办、已知问题与未决问题"),
        ("Changelist", "./changelist.html", "跨文档变更流水线"),
    ]
    quick_html = "\n".join(
        f"""<li class="chapter-card">
          <a href="{html.escape(href)}">
            <span class="chapter-number">{html.escape(label)}</span>
            <span class="chapter-content">
              <span class="chapter-title">{html.escape(label)}</span>
              <span class="chapter-description">{html.escape(desc)}</span>
            </span>
          </a>
        </li>"""
        for label, href, desc in quick_links
    )
    section_html: list[str] = []
    for section in sections:
        cards: list[str] = []
        for doc_id, href, title, desc in section["items"]:
            path = href.removeprefix("./")
            cards.append(
                f"""<li class="chapter-card">
          <a href="{html.escape(href)}">
            <span class="chapter-number">{html.escape(doc_id)}</span>
            <span class="chapter-content">
              <span class="chapter-title">{html.escape(title)}</span>
              <span class="chapter-description">{html.escape(desc)} · {html.escape(path)}</span>
            </span>
          </a>
        </li>"""
            )
        section_html.append(
            f"""<section class="doc-section set-section" id="{html.escape(section["kind"])}">
      <header>
        <h2>{html.escape(section["title"])}</h2>
        <p class="doc-meta">{html.escape(section["kind"])} · {len(section["items"])} docs</p>
      </header>
      <p>{html.escape(section["label"])}</p>
      <ul class="chapter-list">
{chr(10).join(cards)}
      </ul>
    </section>"""
        )
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="open-novel-docs-renderer">
  <title>Open Novel — 文档索引</title>
  <style>
{style}
  </style>
  <!-- {GENERATED} -->
</head>
<body>
{render_topbar("./", "文档索引")}
<aside class="sidebar" aria-label="Document set navigation">
  <p class="nav-title">文档集</p>
  <nav class="toc">
    <ol>
      <li><a href="#top"><span>00</span>概览</a></li>
{sidebar_links}
    </ol>
  </nav>
</aside>
  <article class="doc set-index" id="top">
    <header class="doc-header">
      <p class="doc-kicker">Open Novel Documentation Set</p>
      <h1>Open Novel</h1>
      <p class="doc-summary">AI 中文长篇小说创作工作台的产品计划、技术规格、迁移记录和执行档案。首页只展示读者会直接打开的文档入口,维护源文件保留在仓库中,不进入主目录。</p>
      <div class="doc-meta" aria-label="Document metadata">
        <span>{total} docs</span>
        <span>{len(sections)} sections</span>
        <span>GitHub Pages ready</span>
      </div>
    </header>
    <main>
      <section class="doc-section set-section" id="quick-links">
        <h2>关键入口</h2>
        <ul class="chapter-list">
{quick_html}
        </ul>
      </section>
{chr(10).join(section_html)}
    </main>
    <footer class="doc-footer">Open Novel docs · static CAST render · GitHub Pages ready</footer>
  </article>
</body>
</html>
"""


def render_all(manifest: dict, *, bootstrap: bool) -> dict[Path, str]:
    if bootstrap:
        bootstrap_source(TODO_SOURCE, ROOT / "todo.html", "todo", "TODO - Open Novel")
        bootstrap_source(CHANGELIST_SOURCE, ROOT / "CHANGELOG.html", "changelist", "Changelist - Open Novel")

    rendered: dict[Path, str] = {
        ROOT / "index.html": render_index(manifest),
        ROOT / "todo.html": render_source_doc(TODO_SOURCE, ROOT / "todo.html", ROOT / "todo.html", "todo", "TODO - Open Novel"),
        ROOT / "changelist.html": render_source_doc(CHANGELIST_SOURCE, ROOT / "changelist.html", ROOT / "CHANGELOG.html", "changelist", "Changelist - Open Novel"),
        ROOT / "CHANGELOG.html": render_compat_changelog(),
    }

    for path in html_paths_from_manifest(manifest):
        if path in rendered or path.name == "index.html":
            continue
        if not path.exists():
            raise FileNotFoundError(f"manifest references missing file: {path.relative_to(ROOT)}")
        text = read_text(path)
        inner = extract_main_inner(text)
        title = extract_title(path, text, inner)
        rendered[path] = render_doc(path, title, inner)
    return rendered


def check_fresh(rendered: dict[Path, str]) -> list[str]:
    failures: list[str] = []
    for path, expected in rendered.items():
        if not path.exists():
            failures.append(f"missing rendered file: {path.relative_to(ROOT)}")
        elif read_text(path) != expected:
            failures.append(f"stale rendered file: {path.relative_to(ROOT)}")
    return failures


def collect_local_hrefs(text: str) -> list[str]:
    without_scripts = re.sub(r"<script\b.*?</script>", "", text, flags=re.S | re.I)
    html_hrefs = re.findall(r"""href=["']([^"']+)["']""", without_scripts)
    markdown_hrefs: list[str] = []
    if not re.search(r"<html\b", text, flags=re.I):
        markdown_hrefs = re.findall(r"""(?<!!)\[[^\]]+\]\(([^)]+)\)""", text)
    return html_hrefs + markdown_hrefs


def validate_links(paths: list[Path]) -> list[str]:
    failures: list[str] = []
    for path in paths + [ROOT / "README.md"]:
        if not path.exists():
            continue
        text = read_text(path)
        ids = set(re.findall(r"""id=["']([^"']+)["']""", text))
        for href in collect_local_hrefs(text):
            if href.startswith(("http://", "https://", "mailto:", "javascript:")):
                continue
            if href.startswith("#"):
                if href[1:] and unquote(href[1:]) not in ids:
                    failures.append(f"{path.relative_to(ROOT)}: missing anchor {href}")
                continue
            split = urlsplit(href)
            raw_path = split.path
            if not raw_path:
                continue
            target = (path.parent / unquote(raw_path)).resolve()
            try:
                target.relative_to(ROOT)
            except ValueError:
                failures.append(f"{path.relative_to(ROOT)}: link escapes repo {href}")
                continue
            if not target.exists():
                failures.append(f"{path.relative_to(ROOT)}: missing link target {href}")
                continue
            if split.fragment and target.suffix == ".html":
                target_ids = set(re.findall(r"""id=["']([^"']+)["']""", read_text(target)))
                if unquote(split.fragment) not in target_ids:
                    failures.append(f"{path.relative_to(ROOT)}: missing target anchor {href}")
    return failures


def validate_strict_profile(manifest: dict) -> list[str]:
    failures: list[str] = []
    required = [
        ROOT / "README.md",
        ROOT / "index.html",
        TODO_SOURCE,
        CHANGELIST_SOURCE,
        ROOT / "todo.html",
        ROOT / "changelist.html",
        ROOT / "plan",
        ROOT / "spec",
    ]
    for path in required:
        if not path.exists():
            failures.append(f"strict profile missing: {path.relative_to(ROOT)}")
    index = read_text(ROOT / "index.html") if (ROOT / "index.html").exists() else ""
    for href in [GITHUB_README_URL, "plan/01-overview.html", "spec/00-version-audit.html", "todo.html", "changelist.html"]:
        if href not in index:
            failures.append(f"index.html does not link {href}")
    if "README.md" in index:
        failures.append("index.html links local README.md instead of the GitHub README")
    for href in [".cast-docs/project.json", "assets/docs.css", "site/docs.json", "site/todo.json", "site/changelist.json"]:
        if href in index:
            failures.append(f"index.html exposes internal maintenance link {href}")
    for path in html_paths_from_manifest(manifest):
        if not path.exists():
            continue
        text = read_text(path)
        rel = path.relative_to(ROOT)
        if "<style>" not in text:
            failures.append(f"{rel}: missing inline style block")
        if '<article class="doc' not in text:
            failures.append(f"{rel}: missing CAST article.doc shell")
        if "<link" in text or "<script" in text:
            failures.append(f"{rel}: scripts or external stylesheets are not allowed")
        if "mailto:" in text:
            failures.append(f"{rel}: mailto links are outside the CAST HTML profile")
    return failures


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--bootstrap", action="store_true", help="create site/todo.json and site/changelist.json from existing HTML if missing")
    parser.add_argument("--check", action="store_true", help="fail if generated artifacts are stale")
    parser.add_argument("--validate", action="store_true", help="run local link and strict profile validation")
    args = parser.parse_args(argv)

    manifest = load_manifest()
    rendered = render_all(manifest, bootstrap=args.bootstrap)

    failures: list[str] = []
    if args.check:
        failures.extend(check_fresh(rendered))
    else:
        for path, text in rendered.items():
            write_text(path, text)

    if args.validate:
        failures.extend(validate_strict_profile(manifest))
        failures.extend(validate_links(html_paths_from_manifest(manifest)))

    if failures:
        for failure in failures:
            print(f"[docs] {failure}", file=sys.stderr)
        return 1
    print(f"[docs] ok ({len(rendered)} HTML artifacts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
